# Site settings

title: Fablab Organization Website
description: "A directory for the Fab Lab ecosystem."
about: ""
url: https://fablaborg.github.io/
email: info@fabfoundation.org



# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 171717
  secondary: e2e2e2
  blacks: 171717 
  whites: ffffff
  blue: 1b3457
  red: f13c53
  green: 27b580
  gray: fafafa

fonts: 
  primary: Helvetica Neue
  secondary: Karla

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:info@fabfoundation.org
  - title: twitter
    url: https://twitter.com/fabfndn
  - title: facebook
    url: https://www.facebook.com/fabfndn


# Team names, titles and social links
people:
- name: 
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 
  pic: 2
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 
  pic: 3
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Postal address (add as many lines as necessary)
address:
  - line: The Fab Foundation
  - line: 50 Milk St., 16th Floor
  - line: Boston, MA 02109

# Build settings
markdown: kramdown
permalink: pretty


# Gems
gems:
  - kramdown



